version: "3"

services:
  minecraft-server:
    image: itzg/minecraft-server:java17
    container_name: minecraft-server
    restart: "no"
    ports:
      - 25566:25565
    environment:
      EULA: "TRUE"
