java:
  gateways:
    default:
      listeners:
        default:
          bind: :25565
  servers:
    default:
      gateways:
        - default
      domains:
        - "*"
      address: example.com:25565
      #proxyBind: 0.0.0.0
      #sendProxyProtocol: true
      #sendRealIP: true
      #overrideStatus:
        #versionName: Infrared
        #maxPlayerCount: 20
        #playerCount: 0
        #
      bandwidth:
        trafficLimit: 1TB
        resetCron: "0 0 0 1 * *"
