java:
  gateways:
    default:
      listeners:
        default:
          bind: :25565
  servers:
    myserver:
      gateways:
        - default
      domains:
        - "*"
      address: example.com:25565
      overrideStatus:
        versionName: Infrared
        maxPlayerCount: 777777777
        playerCount: 2
  # Configuration for webhooks
  webhooks:
    # A webhook defined by an ID. In this case "default"
    mywebhook:
      # Gateway IDs to listen for events to. All events that the connection triggers
      # have also the gateway ID attached to them.
      gatewayIds:
        - default
      # The URL to POST the JSON to
      url: https://example.com/callback
      # Event Topics to listen for
      events:
        - PlayerJoin
        - PlayerLeave