api:
  bind: 0.0.0.0:8080

bedrock:
  chanCap:
    connProcessor: 100
    server: 100
    connPool: 10
  processingNode:
    count: 10
    clientTimeout: 100ms
  gateways:
    mygateway:
      listeners:
        - bind: 0.0.0.0:19132
      servers:
        - myserver
  servers:
    myserver:
      domains:
        - "*"
      address: your-server-address:19132
      webhooks:
        - mywebhook

java:
  chanCap:
    connProcessor: 100
    server: 100
    connPool: 10
  processingNode:
    count: 10
    clientTimeout: 50ms
  gateways:
    mygateway:
      listeners:
        - bind: 0.0.0.0:25565
      servers:
        - myserver
  servers:
    myserver:
      domains:
        - "*"
      address: your-server-address:25565
      overrideStatus:
        versionName: Infrared
        iconPath: ./icon.png
        maxPlayerCount: 777777777
        playerCount: 2
        playerSample:
          - name: Steve
            uuid: 8667ba71-b85a-4004-af54-457a9734eed7
          - name: Alex
            uuid: ec561538-f3fd-461d-aff5-086b22154bce

webhooks:
  mywebhook:
    url: https://your-domain.com/callback
    events:
      - PlayerJoin
      - PlayerLeave

# These are default values that can be overridden
defaults:
  bedrock:
    gateway:
      listener:
        pingStatus:
          edition: MCPE
          protocolVersion: 471
          versionName: "1.17.41"
          playerCount: 0
          maxPlayerCount: 10
          gameMode: SURVIVAL
          gameModeNumeric: 1
          motd: |
            Infrared 2.0
            Join!
      serverNotFoundMessage: Sorry {{username}}, but {{serverDomain}} was not found.
    server:
      dialTimeout: 1s
      dialTimeoutMessage: Sorry {{username}}, but the server is not reachable.
      
  java:
    gateway:
      listener:
        serverNotFoundMessage: Sorry {{username}}, but {{serverDomain}} was not found.
        serverNotFoundStatus:
          versionName: Infrared
          protocolNumber: 0
          maxPlayerCount: 0
          playerCount: 0
          iconPath: ./icon.png
          motd: |
            Infrared 2.0
            {{serverDomain}} was not found.
    server:
      dialTimeout: 1s
      dialTimeoutMessage: Sorry {{username}}, but the server is not reachable.
      dialTimeoutStatus:
        versionName: Infrared
        protocolNumber: 0
        maxPlayerCount: 0
        playerCount: 0
        iconPath: ./icon.png
        motd: |
          Infrared 2.0
          {{serverDomain}} is not reachable.

  webhook:
    dialTimeout: 1s