api:
  bind: 0.0.0.0:8080

bedrock:
  processing_nodes:
    count: 10
  gateways:
    mygateway:
      listeners:
        - bind: 0.0.0.0:19132
      servers:
        - myserver
  servers:
    myserver:
      domains:
        - "*"
      address: your-server-address:19132
      webhooks:
        - mywebhook

java:
  processing_nodes:
    count: 10
  gateways:
    mygateway:
      listeners:
        - bind: 0.0.0.0:25565
      servers:
        - myserver
  servers:
    myserver:
      domains:
        - "haveachin.de"
      address: your-server-address:25565
      override_status:
        version_name: Infrared 1.17
        icon_path: ./icon.png
        max_player_count: 777777777
        player_count: 2
        player_sample:
          - name: Steve
            uuid: 8667ba71-b85a-4004-af54-457a9734eed7
          - name: Alex
            uuid: ec561538-f3fd-461d-aff5-086b22154bce
      webhooks:
        - mywebhook

webhooks:
  mywebhook:
    url: https://your-domain.com/callback
    events:
      - PlayerJoin
      - PlayerLeave

# These are default values that can be overridden
defaults:
  bedrock:
    gateway:
      listener:
        ping_status:
          edition: MCPE
          protocol_version: 471
          version_name: "1.17.41"
          player_count: 0
          max_player_count: 10
          game_mode: SURVIVAL
          game_mode_numeric: 1
          motd: |
            Proxy Host XY
            Join!
      server_not_found_message: Sorry {{username}}, but {{serverDomain}} was not found
    server:
      dial_timeout: 1s
      dial_timeout_message: Sorry {{username}}, but the server is currently unreachable
      
  java:
    gateway:
      listener:
        server_not_found_message: Sorry {{username}}, but {{serverDomain}} was not found
        server_not_found_status:
          version_name: Proxy Host XY
          protocol_number: 757
          max_player_count: 10
          player_count: 0
          icon_path: ./icon.png
          motd: |
            Proxy Host XY
            {{serverDomain}} is not reachable.
    server:
      dial_timeout: 1s
      dial_timeout_message: Sorry {{username}}, but the server is offline.
      dial_timeout_status:
        version_name: Proxy Host XY
        protocol_number: 757
        max_player_count: 10
        player_count: 0
        icon_path: ./icon.png
        motd: |
          Proxy Host XY
          {{serverDomain}} is not reachable.

  webhook:
    dial_timeout: 1s